services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
