export enum MediaGenre {
  // Gêneros compartilhados entre múltiplas mídias
  ACTION = "Action",
  ADVENTURE = "Adventure",
  FANTASY = "Fantasy",
  SCI_FI = "Ficção Científica",
  HORROR = "Horror",
  THRILLER = "Thriller",
  COMEDY = "Comédia",
  DRAMA = "Drama",
  ROMANCE = "Romance",
  CRIME = "Crime",
  MYSTERY = "Mistério",
  WESTERN = "Western",
  WAR = "Guerra",
  HISTORICAL = "Histórico",
  BIOGRAPHY = "Biografia",
  MUSICAL = "Musical",
  SPORTS = "Esportes",
  DOCUMENTARY = "Documentário",

  // Games específicos
  RPG = "RPG",
  FPS = "FPS",
  TPS = "TPS",
  MOBA = "MOBA",
  RTS = "RTS",
  MMORPG = "MMORPG",
  SURVIVAL = "Survival",
  OPEN_WORLD = "Open World",
  SANDBOX = "Sandbox",
  PLATFORMER = "Platformer",
  PUZZLE = "Puzzle",
  ROGUELIKE = "Roguelike",
  SIMULATION = "Simulation",
  STRATEGY = "Strategy",
  FIGHTING = "Fighting",
  RACING = "Racing",
  BATTLE_ROYALE = "Battle Royale",

  // Movies específicos
  SUPERHERO = "Super-herói",
  DISASTER = "Catástrofe",
  MARTIAL_ARTS = "Artes Marciais",
  FILM_NOIR = "Film Noir",
  SLASHER = "Slasher",
  PSYCHOLOGICAL = "Psicológico",
  ANIMATION = "Animação",
  FAMILY = "Família",

  // Series específicos
  MOCKUMENTARY = "Mockumentary",
  SPACE = "Espacial",
  PERIOD_DRAMA = "Drama de Época",
  LEGAL_DRAMA = "Drama Jurídico",
  MEDICAL_DRAMA = "Drama Médico",
  POLICE_PROCEDURAL = "Procedural Policial",
  TEEN_DRAMA = "Drama Adolescente",
  SITCOM = "Sitcom",
  REALITY = "Reality Show",
  TALK_SHOW = "Talk Show",
  MINISERIES = "Minissérie",

  // Books específicos
  EPIC = "Épico",
  CHILDREN = "Infantil",
  YOUNG_ADULT = "Young Adult",
  MAGICAL_REALISM = "Realismo Mágico",
  DYSTOPIAN = "Distopia",
  UTOPIAN = "Utopia",
  GOTHIC = "Gótico",
  HISTORICAL_FICTION = "Ficção Histórica",
  SCIENCE_FICTION = "Ficção Científica",
  SELF_HELP = "Autoajuda",
  POETRY = "Poesia",
  ESSAY = "Ensaio",
  TRAVEL = "Viagem",
  TRUE_CRIME = "True Crime",

  // Music específicos
  POP = "Pop",
  RNB = "R&B",
  DANCE = "Dance",
  ROCK = "Rock",
  HARD_ROCK = "Hard Rock",
  METAL = "Metal",
  PUNK = "Punk",
  INDIE = "Indie",
  ALTERNATIVE = "Alternative",
  HIP_HOP = "Hip Hop",
  RAP = "Rap",
  COUNTRY = "Country",
  FOLK = "Folk",
  JAZZ = "Jazz",
  BLUES = "Blues",
  CLASSICAL = "Clássico",
  ELECTRONIC = "Eletrônica",
  REGGAE = "Reggae",
  LATIN = "Latina",
  K_POP = "K-Pop",
  J_POP = "J-Pop",
  GOSPEL = "Gospel",
  WORLD = "World Music",
  INSTRUMENTAL = "Instrumental"
}